cardrange:
  load-on-startup: false
  cache-enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pgdb
    username: panlookup
    password: randompwd3ds
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

#    properties:
#      hibernate.jdbc.batch_size: 10000
#      hibernate.order_inserts: true
#      hibernate.order_updates: true
